theme: jekyll-theme-minimal
title: Venkatesh Rao presents
description: S.O.P. (Standard operating procedures)
logo: ./logo.png
show_downloads: "true"
google_analytics: [Your Google Analytics tracking ID]
